/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new account
         * @description Hashes the password with Argon2id, creates a fresh user with no historical check-ins, and sets a 7-day httpOnly session cookie. Subsequent calls to /auth/me will return the user.
         */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email + password
         * @description Verifies the Argon2id hash and (on success) sets the same 7-day httpOnly session cookie used by signup.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear the session cookie
         * @description Always returns 204. The frontend should treat this as authoritative log-out.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the currently signed-in user
         * @description Used by the frontend on app load to hydrate the auth slice.
         */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a voice check-in (legacy single-blob upload)
         * @description Accepts an audio recording (multipart/form-data, field name "audio") for the signed-in user. The backend stores the audio, forwards it to the Python voice service for Speechmatics transcription and thymia Sentinel biomarker analysis, persists the result, runs divergence detection against the user history, and returns the full pipeline output. Kept as a fallback when the conversational LiveKit agent isn't reachable.
         */
        post: operations["CheckinsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkins/from-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalise a check-in from the LiveKit voice-agent worker
         * @description Called by the voice-agent worker after a conversational check-in ends. The agent has already captured the user audio, sent it to the voice-service for biomarker analysis, and now hands the transcript + biomarkers + the userId (read from the LiveKit room metadata that the backend minted) to us for persistence + divergence detection. Authenticated by the X-Agent-Secret header.
         */
        post: operations["CheckinsController_createFromSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triage-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List triage events for the signed-in user
         * @description Returns every divergence event the system has detected for the authenticated user, ordered by triggeredAt descending. Each event carries a snapshot of the user trajectory so the packet can render without a second call.
         */
        get: operations["TriageController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/triage-events/{id}/packet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate a one-page triage packet PDF
         * @description Produces a one-page PDF summary of the divergence event suitable for handing to a GP. Streams application/pdf bytes.
         */
        get: operations["TriageController_packet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trajectory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the signed-in user trajectory
         * @description Returns every check-in for the authenticated user ordered by recordedAt ascending, with the PHQ-9 and GAD-7 composite scores and a flag indicating whether each point triggered a divergence event.
         */
        get: operations["TrajectoryController_getTrajectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questionnaire/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest PHQ-9 + GAD-7 totals over the last 14 days
         * @description Aggregates the user's most recent PHQ-9 and GAD-7 item responses (asked by the voice agent during check-ins) into the standard total scores and severity bands. Items are deduped to the most recent answer within the rolling window; missing items are mean-imputed so partial coverage still yields a comparable 0-27 / 0-21 number.
         */
        get: operations["QuestionnaireController_latest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the signed-in user baseline
         * @description Returns the user personal baseline mean and standard deviation for the PHQ-9 and GAD-7 composites computed over the first fourteen check-ins. Returns null composites with isEstablished=false until at least seven check-ins exist.
         */
        get: operations["BaselineController_getBaseline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a LiveKit access token for the conversational check-in
         * @description Mints a short-lived JWT for the signed-in user, generates a fresh room name, and instructs LiveKit Cloud to dispatch the olando-checkin agent worker into that room. The agent receives the userId via room metadata so it can post the resulting check-in back under the right account.
         */
        post: operations["SessionsController_issueToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @description Service status indicator.
             * @example ok
             */
            status: string;
            /**
             * Format: date-time
             * @description Server timestamp at the moment of the health check.
             * @example 2026-04-18T14:00:00.000Z
             */
            timestamp: string;
        };
        SignupDto: {
            /**
             * Format: email
             * @description Email address used as the unique login handle.
             * @example devansh@example.com
             */
            email: string;
            /**
             * @description Plain-text password — hashed with Argon2id before storage.
             * @example a-decent-password
             */
            password: string;
            /**
             * @description Friendly name shown on the dashboard and to the voice agent.
             * @example Devansh
             */
            displayName: string;
        };
        AuthUserDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
        };
        AuthResponseDto: {
            user: components["schemas"]["AuthUserDto"];
        };
        LoginDto: {
            /**
             * Format: email
             * @example devansh@example.com
             */
            email: string;
            password: string;
        };
        CreateCheckinDto: {
            /**
             * Format: binary
             * @description Audio recording (wav, webm, mp3, m4a, ogg). Max 25 MB.
             */
            audio: string;
            /**
             * @description Optional self-rating from 1 (terrible) to 10 (excellent).
             * @example 6
             */
            selfRating?: number;
        };
        BiomarkersDto: {
            anhedonia: number | null;
            lowMood: number | null;
            sleepIssues: number | null;
            lowEnergy: number | null;
            appetite: number | null;
            worthlessness: number | null;
            concentration: number | null;
            psychomotor: number | null;
            nervousness: number | null;
            uncontrollableWorry: number | null;
            excessiveWorry: number | null;
            troubleRelaxing: number | null;
            restlessness: number | null;
            irritability: number | null;
            dread: number | null;
            distress: number | null;
            stress: number | null;
            burnout: number | null;
            fatigue: number | null;
            lowSelfEsteem: number | null;
        };
        /**
         * @description Which composite (PHQ-9 or GAD-7) crossed threshold.
         * @enum {string}
         */
        DivergenceComposite: "phq9" | "gad7";
        TrajectoryPointDto: {
            /**
             * Format: uuid
             * @description Identifier of the check-in this point represents.
             */
            checkinId: string;
            /**
             * Format: date-time
             * @description Timestamp of the check-in.
             */
            recordedAt: string;
            /**
             * @description Mean of the eight Apollo depression dimensions for this check-in (0-1).
             * @example 0.42
             */
            phq9Composite: number | null;
            /**
             * @description Mean of the seven Apollo anxiety dimensions for this check-in (0-1).
             * @example 0.38
             */
            gad7Composite: number | null;
            /**
             * @description Whether this check-in triggered a divergence event.
             * @example false
             */
            triggeredDivergence: boolean;
            /** @description Per-dimension Apollo + Helios biomarker readings (0-1) for this check-in. Null if the voice service was unavailable. */
            biomarkers: components["schemas"]["BiomarkersDto"] | null;
        };
        TriageEventDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            triggeredAt: string;
            /** @description Which composite (PHQ-9 or GAD-7) crossed threshold. */
            composite: components["schemas"]["DivergenceComposite"];
            /** @description Human-readable explanation of the threshold crossing. */
            triggerReason: string;
            /** Format: uuid */
            triggeringCheckinId: string;
            /** @description Personal baseline mean. */
            baselineMean: number;
            /** @description Personal baseline standard deviation. */
            baselineStddev: number;
            /** @description Seven-day rolling average that crossed threshold. */
            observedValue: number;
            /** @description Snapshot of the user trajectory at the moment of this event so the packet can render the chart without a second API call. */
            trajectory: components["schemas"]["TrajectoryPointDto"][];
        };
        CheckinResponseDto: {
            /**
             * Format: uuid
             * @description Identifier of the new check-in.
             */
            checkinId: string;
            /** Format: date-time */
            recordedAt: string;
            /** @description Speechmatics medical-domain transcript of the recording. */
            transcript: string | null;
            /** @description Apollo and Helios biomarker readings on a 0-1 scale, or null if the voice service was unavailable. */
            biomarkers: components["schemas"]["BiomarkersDto"] | null;
            /** @description PHQ-9 composite (mean of Apollo depression dimensions). */
            phq9Composite: number | null;
            /** @description GAD-7 composite (mean of Apollo anxiety dimensions). */
            gad7Composite: number | null;
            /** @description Whether this check-in tripped the divergence detector. */
            divergenceDetected: boolean;
            /** @description The triage event that was created for this check-in, if one was triggered. */
            triageEvent: components["schemas"]["TriageEventDto"] | null;
        };
        QuestionnaireAnswerDto: {
            /** @example phq9.3 */
            questionId: string;
            /** @description Standard PHQ/GAD response level the LLM mapped the user reply onto: 0 = Not at all, 1 = Several days, 2 = More than half the days, 3 = Nearly every day. */
            score: number;
            /** @description Verbatim user reply. Useful for clinician audit / re-scoring. */
            rawAnswer?: string;
        };
        FromSessionCheckinDto: {
            /**
             * Format: uuid
             * @description ID of the user the check-in belongs to. The agent reads this from the LiveKit room metadata that the backend baked into the session token, so it is trusted (the dispatcher only sends rooms minted by us).
             */
            userId: string;
            /**
             * @description LiveKit room/session identifier so we can correlate logs.
             * @example ol-demo-2026-04-18T19-22-11
             */
            sessionId?: string;
            /** @description Speechmatics transcript of the user side of the conversation. */
            transcript: string | null;
            /** @description Biomarker readings produced by the voice-service from the user audio. */
            biomarkers: components["schemas"]["BiomarkersDto"] | null;
            /**
             * @description Total seconds of user audio captured during the session.
             * @example 42.7
             */
            audioDurationSec: number;
            /** @description Server-side path where the agent persisted the user audio (optional). */
            audioStoragePath?: string;
            /** @description PHQ-9 / GAD-7 item answers the agent extracted during the session. Each one carries the standard 0-3 score plus the verbatim user reply for audit. The backend will dedupe unknown ids and out-of-range scores defensively. */
            questionnaireResponses?: components["schemas"]["QuestionnaireAnswerDto"][];
        };
        TriageEventListResponseDto: {
            data: components["schemas"]["TriageEventDto"][];
            /** @example 1 */
            total: number;
        };
        TrajectoryResponseDto: {
            /** @description Trajectory points ordered ascending by recordedAt. */
            data: components["schemas"]["TrajectoryPointDto"][];
            /**
             * @description Total number of points returned.
             * @example 14
             */
            total: number;
        };
        InstrumentSummaryDto: {
            /** @enum {string} */
            instrument: "phq9" | "gad7";
            /** @description Standard PHQ-9/GAD-7 scoring: SUM of item responses (0-3 each) within the rolling window. PHQ-9 here is effectively the PHQ-8 since item 9 (suicidal ideation) is covered by the agent's safety prompt rather than asked directly — the PHQ-8 uses the same severity bands as PHQ-9 (Kroenke 2009), so the number is directly comparable. GAD-7 sums all 7 items. Null if the user has answered nothing in the window. */
            total: number | null;
            /** @description Maximum possible total given the items we ask: 24 for PHQ-9 (PHQ-8 max — item 9 excluded), 21 for GAD-7. */
            maxScore: number;
            /**
             * @description Standard severity band derived from `total`. Bands are: 0-4 minimal · 5-9 mild · 10-14 moderate · 15-19 moderately severe · 20+ severe (PHQ-9 / PHQ-8); 0-4 minimal · 5-9 mild · 10-14 moderate · 15+ severe (GAD-7). Null when `total` is null OR when `coverageValid` is false (we refuse to derive a severity band from incomplete coverage to stay honest with the published scoring rules).
             * @enum {string|null}
             */
            severity: "minimal" | "mild" | "moderate" | "moderately_severe" | "severe" | null;
            /** @description Number of distinct items the user has answered inside the rolling window (deduped to most recent per item). */
            itemsAnswered: number;
            /** @description Number of items the agent actually rotates through. PHQ-9 = 8 (Q9 excluded), GAD-7 = 7. This is what `itemsAnswered` is judged against for coverage. */
            itemsTotal: number;
            /** @description Number of items in the full published instrument (PHQ-9 = 9, GAD-7 = 7). Mostly for FE labelling so users see "8 of 9 PHQ-9 items". */
            itemsPublished: number;
            /** @description True when ≥80% of rotatable items have been answered in the window. This is the validity rule from the original PHQ-9 manual (Spitzer/Kroenke) — below 80% coverage the score is reported but `severity` is suppressed. */
            coverageValid: boolean;
            /**
             * Format: date-time
             * @description Most recent answer timestamp for any item in this instrument. Null if none.
             */
            lastAnsweredAt: string | null;
            /** @description Days the rolling window covers. Standard PHQ-9/GAD-7 ask about the last 14 days. */
            windowDays: number;
        };
        QuestionnaireSummaryResponseDto: {
            phq9: components["schemas"]["InstrumentSummaryDto"];
            gad7: components["schemas"]["InstrumentSummaryDto"];
        };
        CompositeBaselineDto: {
            /**
             * @description Mean of the composite over the baseline window.
             * @example 0.41
             */
            mean: number;
            /**
             * @description Standard deviation of the composite over the baseline window.
             * @example 0.07
             */
            stddev: number;
        };
        BaselineResponseDto: {
            /**
             * @description True once the user has at least seven check-ins so divergence detection can run.
             * @example true
             */
            isEstablished: boolean;
            /**
             * @description Number of check-ins counted toward the baseline.
             * @example 14
             */
            checkinCount: number;
            /** @description Baseline mean and stddev for the PHQ-9 composite. Null until baseline is established. */
            phq9: components["schemas"]["CompositeBaselineDto"] | null;
            /** @description Baseline mean and stddev for the GAD-7 composite. Null until baseline is established. */
            gad7: components["schemas"]["CompositeBaselineDto"] | null;
        };
        SessionTokenResponseDto: {
            /**
             * @description LiveKit Cloud websocket URL the browser should connect to.
             * @example wss://olando-xxxxx.livekit.cloud
             */
            url: string;
            /** @description Short-lived JWT (1 hour) authorising the browser to join the room. */
            token: string;
            /**
             * @description Generated room name. The agent worker dispatches into this same room.
             * @example ol-demo-2026-04-18T19-22-11-1d3f
             */
            roomName: string;
            /**
             * @description Stable identity used for the user participant in the room.
             * @example user-00000000-0000-4000-8000-000000000001
             */
            identity: string;
            /**
             * @description Friendly display name shown to the agent.
             * @example Sam
             */
            displayName: string;
            /**
             * @description Agent worker name that the LiveKit dispatcher will route to.
             * @example olando-checkin
             */
            agentName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description An account with that email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Wrong email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
            /** @description No valid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CheckinsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateCheckinDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinResponseDto"];
                };
            };
            /** @description No valid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Audio file is missing, too large, or has an unsupported MIME type. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CheckinsController_createFromSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Shared secret matching backend env VOICE_AGENT_SHARED_SECRET. */
                "X-Agent-Secret": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FromSessionCheckinDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinResponseDto"];
                };
            };
            /** @description Missing or invalid agent secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TriageController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageEventListResponseDto"];
                };
            };
            /** @description No valid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TriageController_packet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A binary PDF document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description No valid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrajectoryController_getTrajectory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrajectoryResponseDto"];
                };
            };
            /** @description No valid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuestionnaireController_latest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionnaireSummaryResponseDto"];
                };
            };
            /** @description No valid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BaselineController_getBaseline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineResponseDto"];
                };
            };
            /** @description No valid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_issueToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionTokenResponseDto"];
                };
            };
            /** @description No valid session cookie. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description LiveKit credentials missing on the backend. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
